[global]
timezone = "America/Los_Angeles"

[repos.onefake]
repo_url = "/tmp/willnotexist/onefake"
passphrase_command = "exit 1"

[repos.twofake]
repo_url = "/tmp/willnotexist/twofake"
passphrase_command = "exit 1"
